[package]
name = "tour"
version = "0.1.0"
edition = "2024"

[dependencies]
tour-core = { version = "0.1.0", path = "../tour-core", features = ["full"] }
tour-macros = { version = "0.1.0", path = "../tour-macros" }
