[package]
name = "tour-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.101"
tour-parser = { version = "0.1.0", path = "../tour-parser" }

[features]
default = ["dev-reload"]

# reload default to debug_assertions
dev-reload = ["tour-parser/dev-reload"]
